baseURL = "https://jacobtomlinson.dev"
disqusShortname = "jacobtomlinson"
enableRobotsTXT = true
googleAnalytics = "UA-20365477-2"
languageCode = "en-gb"
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength = 15
theme = "working"
title = "Masum Osman"

[params]
SiteSourceURL = "https://github.com/jacobtomlinson/website"
author = "Masum Osman"
avatar = "https://github.com/Masum-Osman/blog-site/blob/master/resources/_gen/images/252019833_1206972469800326_2610539159241774695_n.jpg"
description = "Building RAPIDS and Dask at NVIDIA. Tinker with Opsdroid in my spare time. he/him."
images = ["https://i.imgur.com/Ln3NJU2h.png"]
twitter = "https://twitter.com/masum_osman"
github = "https://github.com/Masum-Osman"

footer_left = "Made with <i class=\"fa fa-heart\"></i> using [Hugo](https://gohugo.io/)</a>"
footer_right = "<i class=\"fa fa-code\"></i> on [Github](https://github.com/jacobtomlinson/jacobtomlinson.github.io) &nbsp;<i class=\"fab fa-github-alt\"></i>"

[permalinks]
posts = "/:section/:year/:title/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[outputFormats]
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"

[markup.goldmark.renderer]
unsafe = true
